spring.application.name=monitoring-spring
# Database Configuration
database.ip = ${DB_IP:db-monitoring}
database.port = ${DB_PORT:5434}
database.user = ${DB_USER:root}
database.password = ${DB_PASSWORD:root}
database.name = ${DB_DBNAME:monitoring-db}

spring.datasource.url = jdbc:postgresql://${database.ip}:${database.port}/${database.name}
spring.datasource.username = ${database.user}
spring.datasource.password = ${database.password}

# JPA/Hibernate Configuration
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true  # Added from Formula1 project

# Deferred datasource initialization (if necessary)
spring.jpa.defer-datasource-initialization=true  

# SQL Initialization Mode
spring.sql.init.mode=always
spring.sql.init.platform=postgres

# Server Configuration
server.port=8083
server.tomcat.threads.max = 1  

# Jackson Configuration
spring.jackson.serialization.fail-on-empty-beans=false  

# JWT Configuration

app.jwtSecret=AppSecretBlaBla  # Same secret across applications
app.jwtExpirationMs=86400000  


